clc;
clear all;
%设置调制信号的采样间隔
BitRate=10000;
%设置仿真时间长度
xSimulationTime=10;
%初始化种子
xInitialSeed=21;
%x表示信噪比的取值范围
x=0:15;
y1=x;
%频率间隔
FrequencySeparation=24000;
%发送端和接收端相对速度(公里/小时）
Velocity=40;
%光速（m/s)
LightSpeed=3*10^8;
%载波频率
Frequency=900*10^6;
%计算载波波长
WaveLenghth=LightSpeed/Frequency;
%最大多普勒频移
fd=Velocity*10^3/3600/WaveLenghth;
for i=1:length(x)
%信噪比依次取向量的值
SNR=x(i);
%执行仿真模型
sim('BFSK_RayleighFading_BER')
y1(i)=xErrorRate(1);
sim('BFSK_AWGN_BER')
y2(i)=xErrorRate2(1);
end
semilogy(x,y1,'-*',x,y2,'-o')
legend('仿真误码率')
xlabel('信噪比（dB)')
ylabel('误码率')
title('瑞利衰落信道下BFSK误码率仿真')
legend('瑞利信道','AWGN信道')